"""dish image

Revision ID: 6e3ebaea5226
Revises: cf3edc377837
Create Date: 2025-11-20 16:45:35.996119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3ebaea5226'
down_revision: Union[str, Sequence[str], None] = 'cf3edc377837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dishes', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dishes', 'image')
    # ### end Alembic commands ###
