"""total em order

Revision ID: 77c88d501fbc
Revises: 6e3ebaea5226
Create Date: 2025-11-20 22:23:13.530853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c88d501fbc'
down_revision: Union[str, Sequence[str], None] = '6e3ebaea5226'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'total')
    # ### end Alembic commands ###
