"""order: delivery_id -> nullable=True

Revision ID: 7acb2a30fac6
Revises: 638bc246295d
Create Date: 2025-11-20 14:18:16.797803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7acb2a30fac6'
down_revision: Union[str, Sequence[str], None] = '638bc246295d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'delivery_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
