"""establishment new columns

Revision ID: cf3edc377837
Revises: 7acb2a30fac6
Create Date: 2025-11-20 16:19:35.051002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3edc377837'
down_revision: Union[str, Sequence[str], None] = '7acb2a30fac6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('establishments', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('establishments', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('establishments', 'address')
    op.drop_column('establishments', 'rating')
    # ### end Alembic commands ###
